// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include <villas/fpga/ips/xmem.h>

/************************** Function Implementation *************************/
#ifndef __linux__
int XMem_CfgInitialize(XMem *InstancePtr, XMem_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_BaseAddress = ConfigPtr->Ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMem_Start(XMem *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMem_ReadReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_AP_CTRL) & 0x80;
    XMem_WriteReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMem_IsDone(XMem *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMem_ReadReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMem_IsIdle(XMem *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMem_ReadReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMem_IsReady(XMem *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMem_ReadReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMem_EnableAutoRestart(XMem *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMem_WriteReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_AP_CTRL, 0x80);
}

void XMem_DisableAutoRestart(XMem *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMem_WriteReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_AP_CTRL, 0);
}

void XMem_Set_axi_master(XMem *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMem_WriteReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_AXI_MASTER_DATA, Data);
}

u32 XMem_Get_axi_master(XMem *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMem_ReadReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_AXI_MASTER_DATA);
    return Data;
}

u32 XMem_Get_value_r(XMem *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMem_ReadReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_VALUE_R_DATA);
    return Data;
}

u32 XMem_Get_value_r_vld(XMem *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMem_ReadReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_VALUE_R_CTRL);
    return Data & 0x1;
}

void XMem_InterruptGlobalEnable(XMem *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMem_WriteReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_GIE, 1);
}

void XMem_InterruptGlobalDisable(XMem *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMem_WriteReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_GIE, 0);
}

void XMem_InterruptEnable(XMem *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMem_ReadReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_IER);
    XMem_WriteReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_IER, Register | Mask);
}

void XMem_InterruptDisable(XMem *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMem_ReadReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_IER);
    XMem_WriteReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_IER, Register & (~Mask));
}

void XMem_InterruptClear(XMem *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMem_WriteReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_ISR, Mask);
}

u32 XMem_InterruptGetEnabled(XMem *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMem_ReadReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_IER);
}

u32 XMem_InterruptGetStatus(XMem *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMem_ReadReg(InstancePtr->Ctrl_BaseAddress, XMEM_CTRL_ADDR_ISR);
}

